Update Ramips-OpenWrt.yml

diff --git a/.github/workflows/Ramips-OpenWrt.yml b/.github/workflows/Ramips-OpenWrt.yml
--- a/.github/workflows/Ramips-OpenWrt.yml
+++ b/.github/workflows/Ramips-OpenWrt.yml
@@ -178,7 +178,7 @@ jobs:
         mkdir -p files/etc/uci-defaults
         cp $GITHUB_WORKSPACE/scripts/init-settings.sh files/etc/uci-defaults/99-init-settings
         echo -e "$(nproc) thread compile"
-        make -j$(nproc) || make -j1 || make -j1 V=s
+        make -j$(nproc) 1>/dev/null 2>build.err || make -j1 1>/dev/null 2>build.err || { echo "::error::Build failed" tail -n 100 build.err make -j1 V=s exit 1 }
         echo "status=success" >> $GITHUB_OUTPUT
         echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
         echo "FILE_DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
